### PR TITLE
add eslint + prettier

### PR DESCRIPTION
**Pull request by linosorice**

### CODE REVIEW

**Comment by m3hari** [comment]
Thanks. Can you add lint command on package.json 

```

 "lint": "node node_modules/eslint/bin/eslint --fix ."


````

Also you need to run lint task and fix the issues that rise.

**Comment by linosorice** [comment]
I'm on it

**Comment by m3hari** [comment]
Hey @linosorice Great job. Thank you very much.

**Comment by m3hari** [comment]
Thanks @linosorice appreciate your contribution! :+1: 

One more thing Can you squash your commits to a single commit and rebase it. otherwise LGTM it's good to be merged.

**Pull request merged**
